### ISSUE TITLE
InitVLOG3__

### ISSUE THREAD

**Issue by pavkamlc** [bartoszek/AUR-colmap-git#2]
This error is the same when upgrade colmap from AUR

/usr/bin/ld: warning: libglog.so.0, needed by /usr/lib/libceres.so.2.1.0, not found (try using -rpath or -rpath-link)
/usr/bin/ld: /usr/lib/libceres.so.2.1.0: undefined reference to `google::InitVLOG3__(int**, int*, char const*, int)'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**Comment by bartoszek** [comment]
Just rebuild 	¯\_(ツ)_/¯
